# Generated by Django 3.1.13 on 2023-03-20 22:25

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=5000, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Tinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=11)),
                ('type', models.CharField(choices=[('active', 'Активный'), ('culture', 'Культурно-познавательный'), ('health', 'Оздоровительный'), ('beach', 'Пляжный')], max_length=200)),
                ('prefered_activities', multiselectfield.db.fields.MultiSelectField(choices=[('sea_activities', 'Загорать и купаться'), ('walking', 'Гулять по городу'), ('for_oldies', 'Посетить санаторий/спа'), ('mountains', 'Подняться в горы'), ('for_masha', 'Сходить в поход'), ('museums', 'Посещать музеи и достопримечательности'), ('sex', 'Развлекаться')], max_length=65)),
                ('person_details', multiselectfield.db.fields.MultiSelectField(choices=[('smart', 'Умный'), ('funny', 'Веселый'), ('versatile', 'Разносторонний'), ('talkative', 'Общительный'), ('brave', 'Смелый')], max_length=37)),
                ('about_me', models.CharField(max_length=300)),
                ('about_second', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.ImageField(upload_to='tours/', verbose_name='Постер')),
                ('place', models.CharField(max_length=30, verbose_name='Место')),
                ('date_start', models.DateField(default=datetime.date.today, verbose_name='Дата выезда')),
                ('date_finish', models.DateField(default=datetime.date.today, verbose_name='Дата окончания')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Стоимость')),
                ('list_of_things', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('complexity', models.CharField(choices=[('basic', 'Базовый'), ('average', 'Средний'), ('advanced', 'Продвинутый'), ('hard', 'Сложный')], max_length=200, verbose_name='Сложность')),
                ('type_of_item', models.CharField(choices=[('tours', 'Туры'), ('directions', 'Направления'), ('excursions', 'Экскурсии'), ('museums', 'Музеи')], max_length=200, verbose_name='Тип выбора')),
                ('comfort', models.CharField(choices=[('basic', 'Базовый'), ('simple', 'Простой'), ('average', 'Средний'), ('above_average', 'Выше среднего'), ('high', 'Высокий')], max_length=200, verbose_name='Комфорт')),
                ('people_in_group', models.PositiveIntegerField(default=1, verbose_name='Максимальное количество людей в группе')),
                ('age', models.PositiveIntegerField(default=10, verbose_name='Минимальный возраст')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
        migrations.CreateModel(
            name='TourShots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='tour_shots/', verbose_name='Изображение')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Кадр из тура',
                'verbose_name_plural': 'Кадры из тура',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тура')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='tour',
            name='type_active',
            field=models.ManyToManyField(to='myapp.Type', verbose_name='типы'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tour', verbose_name='тур'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.reviews', verbose_name='Родитель'),
        ),
    ]
