# Generated by Django 3.1.13 on 2023-03-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20230321_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='url',
            field=models.SlugField(max_length=130, null=True, unique=True),
        ),
    ]
