# Generated by Django 3.1.13 on 2023-03-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_tour_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_client_trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('tour', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tinder_review_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pair', models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], max_length=200)),
                ('what', models.CharField(choices=[('talk', 'Только общались'), ('trip', 'Поехали в путешествие вместе'), ('continue', 'Завязались отношения'), ('married', 'Поженились')], max_length=200)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=200)),
                ('review', models.CharField(max_length=1000)),
            ],
        ),
    ]
